---
deployment:
  tasks:
    - export DEPLOYPATH=/home/apolymen/expenses/
    - /bin/cp -R application $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R system $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH